# Generated by Django 4.2.4 on 2023-08-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('contact_details', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('account_number', models.IntegerField()),
                ('credentials', models.CharField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField()),
                ('scale_size', models.IntegerField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='MeteringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_of_issue', models.DateField()),
                ('model_metering_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.metermodel')),
            ],
        ),
        migrations.CreateModel(
            name='InstalledMeteringDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_date', models.DateField()),
                ('remove_date', models.DateField(null=True)),
                ('metering_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.meteringdevice')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.personalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField()),
                ('time_of_taking', models.DateTimeField()),
                ('metering_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.meteringdevice')),
            ],
        ),
    ]
