# Generated by Django 4.2.4 on 2023-08-20 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalaccount',
            old_name='credentials',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='email',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='last_name',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='sur_name',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indication',
            name='metering_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Indication.installedmeteringdevice'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='account_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
