# Generated by Django 4.2.4 on 2023-08-24 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0003_rename_sur_name_personalaccount_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='code_validity',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 24, 23, 52, 22, 749566)),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='verification_code',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indication',
            name='current_value',
            field=models.IntegerField(max_length=8),
        ),
        migrations.AlterField(
            model_name='meteringdevice',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='patronymic',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='phone_number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
