# Generated by Django 4.2.4 on 2023-08-25 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0004_personalaccount_code_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installedmeteringdevice',
            name='remove_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='code_validity',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 0, 14, 44, 990875)),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
