# Generated by Django 4.2.4 on 2023-08-29 20:53

import Indication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0005_alter_installedmeteringdevice_remove_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedmeteringdevice',
            name='range_of_installation',
            field=models.DateField(default='[2023-11-15, 2023-11-17]'),
            preserve_default=False,
        ),
        migrations.RunSQL("CREATE TABLE Indication_installedmeteringdevice (during tsrange, EXCLUDE USING GIST (during WITH &&));")
        migrations.AlterField(
            model_name='personalaccount',
            name='code_validity',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 20, 52, 46, 285472)),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='phone_number',
            field=models.IntegerField(null=True, validators=[Indication.models.min_phone_value]),
        ),
        migrations.AlterUniqueTogether(
            name='indication',
            unique_together={('metering_device', 'current_value', 'time_of_taking')},
        ),
    ]
