# Generated by Django 4.2.4 on 2023-08-31 21:14

import Indication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0005_alter_installedmeteringdevice_remove_date_and_more'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE Indication_installedmeteringdevice ADD COLUMN range_of_installation tsrange;"),
        migrations.RunSQL("ALTER TABLE Indication_installedmeteringdevice ADD EXCLUDE USING GIST (range_of_installation WITH &&);"),
        migrations.AlterUniqueTogether(
            name='indication',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='indication',
            name='current_value',
            field=models.IntegerField(validators=[Indication.models.max_current_value]),
        ),
        migrations.AlterField(
            model_name='meteringdevice',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='code_validity',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='phone_number',
            field=models.IntegerField(null=True, validators=[Indication.models.min_phone_value]),
        ),
        migrations.AlterUniqueTogether(
            name='indication',
            unique_together={('metering_device', 'current_value', 'time_of_taking')},
        ),
    ]
