# Generated by Django 4.2.4 on 2023-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0006_alter_indication_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='verification_code',
            field=models.CharField(),
        ),
    ]
