# Generated by Django 4.2.5 on 2023-09-26 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Indication', '0008_alter_personalaccount_code_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='code_validity',
            field=models.DateTimeField(default=datetime.datetime(1996, 5, 11, 22, 33, 55, 357625)),
        ),
    ]
