# Generated by Django 4.2.5 on 2023-10-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Indication", "0009_alter_personalaccount_code_validity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personalaccount",
            name="code_validity",
            field=models.DateTimeField(default="1900-01-01 00:00:00"),
        ),
    ]
